#服务器配置
server:
  port: 8800

spring:
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/thymeleaf?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 0206

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5

  #视图层控制
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: classpath:/templates/
      suffix: .html

#Mybatis扫描
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #起别名。可省略写mybatis的xml中的resultType的全路径
  type-aliases-package: com.jemie.practice.thymeleaf.domain
  #  config-location: classpath*:generatorConfig.xml
  # 日志
  logging:
    level:
      com.jemie.practice.thymeleaf.mapper: debug # 显示执行sql